name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: build/*.geode
